export const environment = {
    production: false,
    apiExternal: 'http://localhost:1001/easy-learning/public/v1',
    apiMember: 'http://localhost:1001/easy-learning/member/v1',
    API_URL: 'http://localhost:1001/easy-learning',
    API_VERSION: '/v1',
    USER_URL: '/user',
    ADMIN_URL: '/admin',
    API_ADMIN: "/admin",
    API_PUBLIC: "/public",
    API_MEMBER: "/member",
    API_REPORT: "/report",
    API_CHANGE_REPORT: "/report/change-status",
    API_QUESTION: "/question",
    VERSION_1: "/v1",
    API_USER: "/user",
    API_ROLE: "/role",
    API_USERINFO: "/info",
    API_AVATAR: "/avatar",
    API_PASSWORD: "/password",
    LOCK_USER: "/lock",
    API_CHANGE_STATUS: "/change-status",
    API_GET_TOKEN_FORGOT_PASSWORD: "/get-token-forgot-pass",
    API_FORGOT_PASSWORD: "/forgot-pass",
    API_LOGOUT: "/logout",
    API_SIGNUP: "/sign-up",
    API_AUTHENTICATION: "/authenticate",
    API_LESSON: "/lesson",
    API_VALID_TOKEN: "/valid-token",
    API_QUESTION_TYPE: "/question-type",
    API_ANSWER: "/answer",
    API_INVOICE: "/invoice",
    API_PACKAGE_UPGRADE: "/package-upgrade",
    PATH_ID: "/{id}",
    ID: "id",
    LANGUAGE: "vi",
  };
  